### PR TITLE
Library version is updated to 16.0 in getting-started.md

### PR DESCRIPTION
**Pull request by nutharsh**
I have updated version from 15.0 to 16.0 in both gradle and maven examples in getting-started.md

### CODE REVIEW

**Comment by nutharsh** [comment]
Hi @bbakerman / @andimarek - I have made a small correction to update version to 16.0 in getting-started.md file

**Comment by nutharsh** [comment]
> Hi @bbakerman / @andimarek - I have made a small correction to update version to 16.0 in getting-started.md file

Made changes only in v16 folder and already tested once by running the changes locally via _hugo server -w_ command.

**Comment by nutharsh** [comment]
@bbakerman @andimarek can you please help me in merging this?

**Comment by andimarek** [comment]
We should not use 16.0 but rather 16.1. thanks a lot

**Comment by setchy** [comment]
> We should not use 16.0 but rather 16.1. thanks a lot 

My documentation PR #43 should already be ready to go

**Comment by nutharsh** [comment]
> We should not use 16.0 but rather 16.1. thanks a lot

Fine @andimarek. I will go ahead and close this PR.

**Pull request closed without merging**
